import NavBar from "./components/navbar";
import Footer from "./components/footer";
import { ColorModeScript } from "@chakra-ui/react";
import { Providers } from "./providers";

import "./globals.css";
import theme from "./theme";

//const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ColorModeScript initialColorMode={theme.config.initialColorMode} />
        <NavBar />
        <Providers>{children}</Providers>
        <Footer />
      </body>
    </html>
  );
}
